; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32_c3_supermini]
platform = espressif32
board = lolin_c3_mini
monitor_speed = 115200
framework = arduino
build_flags=
    -DESP32
    -DCRSF_SERIAL=Serial1
    -DCRSF_BAUD_RATE=420000
    -DLED_PORT=8

[env:upesy_wroom]
platform = espressif32
board = upesy_wroom
monitor_speed = 115200
framework = arduino
build_flags=
    -DESP32
    -DCRSF_SERIAL=Serial1
    -DCRSF_BAUD_RATE=420000
    -DLED_PORT=2

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
monitor_speed = 115200
framework = arduino
build_flags=
    -DCRSF_SERIAL=Serial
    -DCRSF_BAUD_RATE=115200
    -DLED_PORT=LED_BUILTIN

[env:pro16MHzatmega328]
platform = atmelavr
board = pro16MHzatmega328
monitor_speed = 115200
framework = arduino
build_flags=
    -DCRSF_SERIAL=Serial
    -DCRSF_BAUD_RATE=115200
    -DLED_PORT=LED_BUILTIN
